### ISSUE TITLE
Error - a Python 2/3 problem?

### ISSUE THREAD

**Issue by OZ1SEJ** [makermovement/3.5-Sensor2Phone#1]
When running this script, I get this error:

        f.write(struct.pack('b',i))
    struct.error: required argument is not an integer

I had to change `print i` to `print(i)`, so I suspect this might be a Python 2 / Python 3 problem?

**Comment by 153armstrong** [comment]
`f.write(struct.pack('b',int(i)))?`

**Comment by OZ1SEJ** [comment]
Looks reasonable, thanks! :-)
